server:
  port: 9090
spring:
  liquibase:
    change-log: classpath:/db/liquibase/dbchangelog-master.xml
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    generate-unique-name: false
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        generate_statistics: "true"
        format_sql: "true"
        ddl-auto: "none"
    show-sql: true
    database-platform: "org.hibernate.dialect.H2Dialect"
logging:
  level:
    org:
      hibernate:
        stat: debug
        type: debug