version: '3.5'

services:

  container-mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=MyAppDb
      - MYSQL_USER=myapp-user
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  jdk-app:
    ports:
      - "8080"
    image: openjdk:11
    hostname: jdk-app
    restart: on-failure
    #    depends_on: container-mysql
    volumes:
      - 'C:\Users\Eugen Barbu\IdeaProjects\EmployeeDemo\target\EmployeeDemo-0.0.1-SNAPSHOT.jar:/app.jar'
    command: [ 'java', '-jar', '/app.jar' ]
    environment:
      - VIRTUAL_HOST=proxy.example
    #  - DATABASE_HOST=myapp-mysql
    #  - DATABASE_USER=myapp-user
    #  - DATABASE_PASSWORD=password
    #  - DATABASE_NAME=MyAppDb
    #  - DATABASE_PORT=3306

  nginix-loadbalancer:
    image: jwilder/nginx-proxy:latest
    volumes:
      - //var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      - DEFAULT_HOST=proxy.example
    ports:
      - "80:80"

networks:
  default:
    driver: bridge
    name: myproject